### ISSUE TITLE
Variation as top level

### ISSUE THREAD

**Issue by NealJMD** [SumOfUs/share_progress#2]
Looking at the [documentation for the ShareProgress API](https://docs.google.com/document/d/1f1Jktt4gk9b3qugH8h-3bj6DoijQ3_6-RxUw5uq7DWU/edit) I notice that variations of buttons for AB testing are specified through the button API as nested parameters. However, for our wrapper it seems like it makes sense to make Variations as a class on a level with buttons. 

We should be able to call `ShareProgress::Variant.new(my_button, variant_options)` rather than `ShareProgress::Button.update(options_including_variant_options_as_nested_hash)`.

**Comment by osahyoun** [comment]
An excellent design choice.

**Comment by EricBoersma** [comment]
Yeah, I think this makes sense
