### ISSUE TITLE
Button vs ButtonClient

### ISSUE THREAD

**Issue by NealJMD** [SumOfUs/share_progress#4]
@EricBoersma the way you wrote the beginning of the Button class, it has an initialize method that starts a connection object for making requests, which is really convenient as I was writing starting to write methods. However, it doesn't semantically really make sense to say `Button.new.all` or `my_button = Button.new; my_button.find(my_id)`. However, those do semantically make sense as `ButtonClient.new.all` etc, so I renamed it to that.

However, I would rather make those class methods of `Button`, so that just like ActiveRecord we can call `Button.all` of `Button.find`. Is there a good way we can refactor the connection stuff so it can be class methods? This also ties into #3.

**Comment by osahyoun** [comment]
@NealJMD I like your suggestion. `Button.all` looks great as an API. My suggestion at https://github.com/SumOfUs/share_progress/pull/6#discussion-diff-37621043 is one way you could refactor the client. So you'd actually express your request directly in `find`, `all`, etc:

``` ruby
class << self
  def all(offset: 5, limit: 100)
    Client.get '/buttons', query: { offset: offset, limit: limit }
  end

  def find(id)
    Client.get "/buttons/#{id}"
  end
end
```

**Comment by EricBoersma** [comment]
I think this makes sense as an API, and the abstraction between Buttons and the Client make sense to me.

Is the need here for the `Client` calls to become class methods, then? I don't think that would be a significant problem.
